# Generated by Django 2.2.4 on 2019-09-22 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaiSan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_tai_san', models.CharField(choices=[('VT', 'Vat tu'), ('TB', 'Thiet bi')], max_length=2)),
                ('ten_tai_san', models.CharField(max_length=20)),
                ('ngay_su_dung', models.DateField()),
                ('thoi_han_bh', models.IntegerField()),
                ('thoi_gian_sd', models.IntegerField(verbose_name='so nam su dung')),
                ('tai_san_cha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanlitaisan.TaiSan')),
            ],
        ),
        migrations.CreateModel(
            name='LichSuBaoTri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_bao_tri', models.DateField()),
                ('noi_dung', models.TextField()),
                ('tai_san_bao_tri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlitaisan.TaiSan')),
            ],
        ),
    ]
