# Generated by Django 2.2.4 on 2019-10-08 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaiSan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_tai_san', models.CharField(choices=[('VT', 'Vật tư'), ('TB', 'Thiết bị')], max_length=2, verbose_name='loại tài sản')),
                ('ten_tai_san', models.CharField(max_length=20, verbose_name='tên tài sản')),
                ('ngay_su_dung', models.DateField(verbose_name='ngày bắt đầu sử dụng')),
                ('thoi_han_bao_hanh', models.PositiveIntegerField(verbose_name='số năm bảo hành')),
                ('thoi_gian_sd', models.PositiveIntegerField(verbose_name='số năm sử dụng')),
                ('tai_san_cha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanlitaisan.TaiSan', verbose_name='Thiết bị chứa')),
            ],
        ),
        migrations.CreateModel(
            name='LichSuBaoTri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_bao_tri', models.DateField(verbose_name='Ngày Bảo Trì')),
                ('noi_dung', models.TextField(verbose_name='Nội dung bảo trì')),
                ('tai_san_bao_tri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlitaisan.TaiSan', verbose_name='Tài sản bảo trì')),
            ],
        ),
    ]
