# Generated by Django 2.2.4 on 2019-10-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlitaisan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lichsubaotri',
            name='tieu_de',
            field=models.CharField(default='Kiem tra', max_length=30, verbose_name='Tiêu đề'),
            preserve_default=False,
        ),
    ]
