# Generated by Django 2.2.4 on 2019-10-14 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlitaisan', '0002_lichsubaotri_tieu_de'),
    ]

    operations = [
        migrations.AddField(
            model_name='taisan',
            name='dia_diem',
            field=models.CharField(default='B602', max_length=20, verbose_name='Địa điểm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taisan',
            name='hien_trang',
            field=models.CharField(choices=[('SD', 'Đang sử dụng'), ('BH', 'Bị hỏng')], default='SD', max_length=2, verbose_name='Hiện trạng'),
            preserve_default=False,
        ),
    ]
