# Generated by Django 2.2.4 on 2019-09-24 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quanlitaisan', '0002_auto_20190922_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lichsubaotri',
            name='ngay_bao_tri',
            field=models.DateField(verbose_name='Ngày Bảo Trì'),
        ),
        migrations.AlterField(
            model_name='lichsubaotri',
            name='noi_dung',
            field=models.TextField(verbose_name='Nội dung bảo trì'),
        ),
        migrations.AlterField(
            model_name='lichsubaotri',
            name='tai_san_bao_tri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlitaisan.TaiSan', verbose_name='Tài sản bảo trì'),
        ),
        migrations.AlterField(
            model_name='taisan',
            name='loai_tai_san',
            field=models.CharField(choices=[('VT', 'Vật tư'), ('TB', 'Thiết bị')], max_length=2, verbose_name='Loại tài sản'),
        ),
        migrations.AlterField(
            model_name='taisan',
            name='ngay_su_dung',
            field=models.DateField(verbose_name='Ngày bắt đầu sử dụng'),
        ),
        migrations.AlterField(
            model_name='taisan',
            name='tai_san_cha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanlitaisan.TaiSan', verbose_name='Thiết bị chứa'),
        ),
        migrations.AlterField(
            model_name='taisan',
            name='ten_tai_san',
            field=models.CharField(max_length=20, verbose_name='Tên tài sản'),
        ),
        migrations.AlterField(
            model_name='taisan',
            name='thoi_gian_sd',
            field=models.PositiveIntegerField(verbose_name='Số năm sử dụng'),
        ),
        migrations.AlterField(
            model_name='taisan',
            name='thoi_han_bao_hanh',
            field=models.PositiveIntegerField(verbose_name='Số năm bảo hành'),
        ),
    ]
