# Generated by Django 2.2.4 on 2019-09-30 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quanlitaisan', '0003_auto_20190924_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='lichsubaotri',
            name='tieu_de',
            field=models.CharField(default='Bảo trì', max_length=30, verbose_name='Tiêu đề'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lichsubaotri',
            name='tai_san_bao_tri',
            field=models.ForeignKey(default='Bảo trì', on_delete=django.db.models.deletion.CASCADE, to='quanlitaisan.TaiSan', verbose_name='Tài sản bảo trì'),
        ),
        migrations.AlterField(
            model_name='taisan',
            name='loai_tai_san',
            field=models.CharField(choices=[('VT', 'Vật tư'), ('TB', 'Thiết bị')], max_length=2, verbose_name='loại tài sản'),
        ),
        migrations.AlterField(
            model_name='taisan',
            name='ngay_su_dung',
            field=models.DateField(verbose_name='ngày bắt đầu sử dụng'),
        ),
        migrations.AlterField(
            model_name='taisan',
            name='ten_tai_san',
            field=models.CharField(max_length=20, verbose_name='tên tài sản'),
        ),
        migrations.AlterField(
            model_name='taisan',
            name='thoi_gian_sd',
            field=models.PositiveIntegerField(verbose_name='số năm sử dụng'),
        ),
        migrations.AlterField(
            model_name='taisan',
            name='thoi_han_bao_hanh',
            field=models.PositiveIntegerField(verbose_name='số năm bảo hành'),
        ),
    ]
