# Generated by Django 2.2.4 on 2019-10-26 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quanlitaisan', '0004_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taisan',
            name='dia_diem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='quanlitaisan.Room'),
        ),
    ]
