# Generated by Django 2.2.4 on 2019-10-29 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quanlitaisan', '0004_nhanvien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taisan',
            name='dia_diem',
        ),
    ]
