# Generated by Django 2.2.4 on 2019-09-30 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quanlitaisan', '0004_auto_20190930_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lichsubaotri',
            name='tai_san_bao_tri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlitaisan.TaiSan', verbose_name='Tài sản bảo trì'),
        ),
    ]
