# Generated by Django 2.2.4 on 2019-10-26 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quanlitaisan', '0005_auto_20191026_2217'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Phong',
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=40, verbose_name='Họ và tên')),
                ('phong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanlitaisan.Phong', verbose_name='Phòng')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='taisan',
            name='phu_trach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanlitaisan.NhanVien', verbose_name='Người phụ trách'),
        ),
    ]
