# Generated by Django 2.2.4 on 2019-10-29 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlitaisan', '0005_remove_taisan_dia_diem'),
    ]

    operations = [
        migrations.AddField(
            model_name='taisan',
            name='dia_diem',
            field=models.CharField(default='B602', max_length=20, verbose_name='Địa điểm'),
            preserve_default=False,
        ),
    ]
