# Generated by Django 2.2.4 on 2019-10-29 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quanlitaisan', '0006_taisan_dia_diem'),
    ]

    operations = [
        migrations.AddField(
            model_name='taisan',
            name='quan_ly',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.SET_DEFAULT, to='quanlitaisan.NhanVien'),
        ),
    ]
