# Generated by Django 2.2.4 on 2019-10-26 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quanlitaisan', '0006_auto_20191026_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phong',
            name='nguoi_phu_trach',
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='QuanLy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nhan_vien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanlitaisan.NhanVien', verbose_name='Nhân viên quản lý')),
                ('phong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlitaisan.Phong', verbose_name='Phòng')),
            ],
        ),
    ]
