# Generated by Django 2.2.7 on 2019-11-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlitaisan', '0007_taisan_quan_ly'),
    ]

    operations = [
        migrations.AddField(
            model_name='taisan',
            name='don_vi_tinh',
            field=models.CharField(choices=[('C', 'Cái'), ('Ch', 'Chiếc'), ('T', 'Tập'), ('KG', 'Kilogram'), ('ML', 'ml')], default='C', max_length=2, verbose_name='Đơn vị tính'),
        ),
        migrations.AddField(
            model_name='taisan',
            name='so_luong',
            field=models.PositiveIntegerField(default=1, verbose_name='Số lượng'),
        ),
    ]
