# Generated by Django 2.2.7 on 2019-11-27 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlitaisan', '0008_auto_20191127_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taisan',
            name='don_vi_tinh',
            field=models.CharField(choices=[('C', 'Cái'), ('Ch', 'Chiếc'), ('T', 'Tập'), ('KG', 'Kilogram'), ('ML', 'ml')], max_length=2, verbose_name='Đơn vị tính'),
        ),
        migrations.AlterField(
            model_name='taisan',
            name='so_luong',
            field=models.PositiveIntegerField(verbose_name='Số lượng'),
        ),
    ]
