# Generated by Django 2.2.7 on 2019-11-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlitaisan', '0009_auto_20191127_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taisan',
            name='don_vi_tinh',
            field=models.CharField(choices=[('C', 'Cái'), ('Ch', 'Chiếc'), ('T', 'Tập'), ('KG', 'Kilogram'), ('ML', 'ml'), ('K', 'Khác')], max_length=2, verbose_name='Đơn vị tính'),
        ),
    ]
