# Generated by Django 2.2.7 on 2019-12-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanlitaisan', '0010_auto_20191127_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhanvien',
            name='department',
            field=models.CharField(default='B702', max_length=20, verbose_name='Phòng ban'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='titlte',
            field=models.CharField(default='Quan ly', max_length=20, verbose_name='Chức vụ'),
            preserve_default=False,
        ),
    ]
