# Generated by Django 2.2.7 on 2019-12-02 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quanlitaisan', '0011_auto_20191202_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nhanvien',
            old_name='titlte',
            new_name='title',
        ),
    ]
